### PR TITLE
Packaging Scash QT wallet with AppImage

### PR DESCRIPTION
**Pull request by dragononcrypto**
Please however try with a different image, I don't think that one is working.

### CODE REVIEW

**Comment by probonopd** [comment]
Where can the AppImage be downloaded?

**Comment by probonopd** [comment]
On https://github.com/scashml/scashcpp/blob/7764fb01ad0f5c66c119096033673c0e11997134/doc/build-appimage.md#L53 it is described how to make an AppImage, would it be possible to provide a readymade one at GitHub Releases?

**Comment by scashml** [comment]
We already made image (https://github.com/scashml/scashbuilds/tree/master/v123/linux/x86_64) but to be honest we are not completely happy with it at the moment, because it uses GLIBCXX of version not supported on systems older than Ubuntu 16.04. This is not the lack of your software, which is great, thank you, but probably we should have to compile it and fully retest on older systems first.

**Comment by probonopd** [comment]
Thanks @scashml - please have a look at https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 regarding the GLIBCXX topic.

**Pull request merged**
